openapi: 3.0.1
info:
  title: Hr service REST endpoints
  description: COA lab1 Вариант 13104 service2
  version: 1.0.0
servers:
  - url: https://localhost:78778/api/v1
tags:
  - name: HR
    description: HR calls basic services
paths:
  /fire/{id}:
    delete:
      tags:
        - HR
      summary: fire worker by id
      operationId: fireWorkerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 0
            exclusiveMinimum: true
            example: 1
      responses:
        "400":
          description: Invalid worker or org id value
          content:
            application/xml:
              schema:
                xml:
                  name: Error
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 400
                  message:
                    type: string
                    example: Invalid worker or org id value
                  time:
                    type: string
                    format: date-time
                    example: 2023-10-13T00:00:00Z
        "500":
          description: Internal server error
          content:
            application/xml:
              schema:
                xml:
                  name: Error
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 500
                  message:
                    type: string
                    example: Internal server error
                  time:
                    type: string
                    format: date-time
                    example: 2023-10-13T00:00:00Z
        default:
          description: Returns error code, message and time in case of error
          content:
            application/xml:
              schema:
                $ref: './WorkerService.yaml#/components/schemas/Error'
  /move/{worker-id}/{id-from}/{id-to}:
    put:
      tags:
        - HR
      summary: fire worker by id
      operationId: moveWorkerById
      parameters:
        - name: worker-id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 0
            exclusiveMinimum: true
            example: 1
        - name: id-from # in our variants there is no id for organization. So i added it as properties of organiztion
          in: path
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 0
            exclusiveMinimum: true
            example: 1
        - name: id-to # in our variants there is no id for organization. So i added it as properties of organiztion
          in: path
          required: true
          schema:
            type: integer
            format: int64
            nullable: false
            minimum: 0
            exclusiveMinimum: true
            example: 1
      responses:
        "200":
          description: All input id valid. Worker now works in another organization.
          content:
            application/xml:
              schema:
                $ref: "./WorkerService.yaml#/components/schemas/WorkerFullInfo"
        "400":
          description: Invalid worker or org id value
          content:
            application/xml:
              schema:
                xml:
                  name: Error
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 400
                  message:
                    type: string
                    example: Invalid worker or org id value
                  time:
                    type: string
                    format: date-time
                    example: 2023-10-13T00:00:00Z
        "500":
          description: Internal server error
          content:
            application/xml:
              schema:
                xml:
                  name: Error
                type: object
                properties:
                  code:
                    type: integer
                    format: int32
                    example: 500
                  message:
                    type: string
                    example: Internal server error
                  time:
                    type: string
                    format: date-time
                    example: 2023-10-13T00:00:00Z
        default:
          description: Returns error code, message and time in case of error
          content:
            application/xml:
              schema:
                $ref: './WorkerService.yaml#/components/schemas/Error'
